### ISSUE TITLE
Update Peertube image

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tf-images#229]
All Peertube instances give ```bad gateway```

**Comment by hossnys** [comment]
- Just built docker image from the current image docker file and started it successfully , then setup caddy server pointing to it's public_ip:9000 , and it worked perfectly 
![Screenshot from 2024-05-19 12-12-20](https://github.com/threefoldtech/tf-images/assets/26298009/f8740405-3033-409e-bcae-70a3fed1ce9e)

- after some investigation with @Omarabdul3ziz we found that in peertube deployment [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/weblets/tf_peertube.vue#L212) is pointing to port 80 not 9000 and this is already changed at this [commit](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/5132df6edbb1959a4ddaae4be1271c3a811b9de8) .
- so dev team need to fix that as the issue is from dashboard code side not the image itself .

**Comment by hossnys** [comment]
- issue fixed here https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2727 , so @zaelgohary please arrange who is gonna verify it , then close this one .

**Comment by zaelgohary** [comment]
Verified [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2727#issuecomment-2119265077)
