### ISSUE TITLE
Ubuntu 22.04 micro VM flist is outdated

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tf-images#264]
If I deploy an Ubuntu 22.04 micro VM today from the Playground, it uses the flist: `hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist`

This flist is not up to date with the changes in this repo and it has a pretty significant issue. The `ssh-init` zinit service definition is not set to oneshot. Therefore the script runs forever in a busy loop! It also overwrites any changes a user tries to make the `authorized_keys` file and invokes `sshd` when there's a dedicated service for that.

Let's replace the flist with one based on the latest Dockerfile in this repo, which does not have these issues.

**Comment by PeterNashaat** [comment]
@maxux Could you please promote [flist](https://github.com/threefoldtech/tf-images/issues/241) https://hub.grid.tf/petep.3bot/threefolddev-ubuntu22.04-latest.flist.md instead of https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist 
it was [tested](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2730#issuecomment-2120000683) and verified .

**Comment by maxux** [comment]
Promoted :)

**Comment by PeterNashaat** [comment]
thanks .
