### ISSUE TITLE
Gitea: Deprecated config option `[mailer].HOST` is present

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tf-images#289]
Cannot test email
Go to ```Gitea > Site Administration > Configuration > SMTP Mailer Configuration```
Enter email and click ```Send```
I got an error ```Deprecated config option `[mailer].HOST` is present, please use `[mailer].SMTP_ADDR` instead. This fallback will be/has been removed in v1.19.0 (and 1 more)```
![image](https://github.com/user-attachments/assets/232a06ce-7957-4c02-b290-a7b90f1c9137)

**Comment by samaradel** [comment]
related to [#3265](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3265)

**Comment by PeterNashaat** [comment]
- As mentioned in the error message mailer.HOST is deprecated config https://docs.gitea.com/administration/config-cheat-sheet#mailer-mailer
- Use `GITEA__mailer__SMTP_ADDR` instead of using`GITEA__mailer__HOST` for smtp config.
  - Tested smtp config and it's working fine
 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/8a29c43c-68f2-45b5-927e-5ec09895995b"> 
<img width="1255" alt="image" src="https://github.com/user-attachments/assets/ed804cf3-2882-44ef-a420-8044dee24b79">
<img width="481" alt="image" src="https://github.com/user-attachments/assets/a9eef11f-0a52-4672-a376-fa556dee87ae">
